name: DMP450
channels:
  - bioconda
  - yhori991
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aria2=1.37.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cairo=1.18.0
  - cuda-cudart=12.8.90
  - cuda-cudart_linux-64=12.8.90
  - cuda-nvrtc=12.8.93
  - cuda-nvtx=12.8.90
  - cuda-version=12.8
  - cudnn=9.15.1.9
  - expat=2.7.3
  - filelock=3.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fsspec=2025.10.0
  - gawk=5.3.1
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.2
  - gnina=1.3.2
  - hdf5=1.14.6
  - icu=73.2
  - jansson=2.14
  - jinja2=3.1.6
  - jsoncpp=1.9.6
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libabseil=20250512.1
  - libaec=1.1.4
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libcblas=3.9.0
  - libcublas=12.8.4.1
  - libcudnn=9.15.1.9
  - libcudnn-dev=9.15.1.9
  - libcurl=8.17.0
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - libnghttp2=1.67.1
  - libnsl=2.0.0
  - libpng=1.6.51
  - libprotobuf=6.31.1
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtorch=2.8.0
  - libuuid=1.41.5
  - libuv=1.51.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2024.2.2
  - mmseqs2=18.8cc5c
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nccl=2.28.9.1
  - ncurses=6.5
  - networkx=3.5
  - openbabel=3.1.1
  - openssl=3.6.0
  - optree=0.14.1
  - pcre2=10.44
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pyquaternion=0.9.9
  - python=3.11.14
  - python_abi=3.11
  - readline=8.3
  - setuptools=80.9.0
  - sleef=3.9.0
  - sqlite=3.51.0
  - sympy=1.14.0
  - tbb=2021.8.0
  - tk=8.6.15
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - attrs==25.4.0
      - biopython==1.84
      - boltz==2.2.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - chembl-structure-pipeline==1.2.2
      - click==8.1.7
      - cuequivariance==0.7.0
      - cuequivariance-ops-cu12==0.7.0
      - cuequivariance-ops-torch-cu12==0.7.0
      - cuequivariance-torch==0.7.0
      - dgl==2.4.0+cu121
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - einx==0.3.0
      - fair-esm==2.0.0
      - fairscale==0.4.13
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - gemmi==0.6.5
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.1
      - hydra-core==1.3.2
      - idna==3.11
      - ihm==2.7
      - joblib==1.5.2
      - lightning-utilities==0.15.2
      - llvmlite==0.44.0
      - lmdb==1.7.5
      - markdown==3.10
      - mashumaro==3.14
      - meeko==0.7.1
      - modelcif==1.2
      - molgrid==0.5.5
      - msgpack==1.1.2
      - multidict==6.7.0
      - numba==0.61.0
      - numpy==2.1.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - platformdirs==4.5.0
      - propcache==0.4.1
      - protobuf==5.29.5
      - psutil==7.1.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - rdkit==2025.3.3
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sentry-sdk==2.47.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - torch==2.9.1
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - triton==3.5.1
      - typer-slim==0.20.0
      - types-requests==2.32.4.20250913
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - unimol-tools==0.1.5
      - urllib3==2.5.0
      - wandb==0.18.7
      - werkzeug==3.1.4
      - yarl==1.22.0
